model_list:
  # chat completion
  - model_name: AzureOpenAI
    litellm_params:
      model: azure/gpt-4o  # "azure/[deployment_name]"
      api_key: os.environ/AZURE_OPENAI_API_KEY
      api_base: os.environ/AZURE_OPENAI_ENDPOINT
      api_version: os.environ/AZURE_OPENAI_API_VERSION
